
create table rateplancharge(
	accounting_code varchar(100),
	apply_discount_to char(1),
	bill_cycle_day integer,
	bill_cycle_type varchar(30),
	billing_period varchar(10),
	billing_period_alignment varchar(50),
	charge_through_date varchar(50),
	charge_model varchar(50),
	charge_number varchar(10),
	charge_type varchar(10),
	charge_created_by varchar(32),
	charge_created_on varchar(50),
	charge_description varchar(100),
	charge_discount_level varchar(10),
	charge_dmrc DECIMAL(22,9),
	charge_dtcv	DECIMAL(22,9),
	effective_end_date varchar(50),
	effective_start_date varchar(50),
	id varchar(32) primary key,
	is_last_segment boolean,
	list_price_base varchar(50),
	mrr decimal(22,9),
	name varchar(100),
	number_of_periods integer,
	original_id varchar(32),
	overage_calculate_option varchar(50),
	overage_unused_units_credit_option varchar(50),
	process_through_date varchar(50),
	quantity decimal(22,9),
	revenue_recognition_rule_name varchar(50),
	rev_rec_code varchar(32),
	rev_rec_trigger_condition varchar(50),
	segment integer,
	specific_billing_period integer,
	tcv decimal(22,9),
	trigger_date varchar(50),
	trigger_event varchar(50),
	uom varchar(10),
	updated_by_id varchar(32),
	updated_on varchar(50),
	upto_periods integer,
	version integer,
	account_id varchar(32),
	subscription_id varchar(32),
	foreign key (account_id) references account(id),
	foreign key (subscription_id) references subscription(id)	
)
sortkey(account_id, subscription_id);



create table account(
	account_number varchar(50) sortkey,
	additional_email_addresses varchar(600),
	allow_invoice_edit boolean,
	autoPay boolean,
	balance DECIMAL(22,9),
	batch varchar(20),
	billcycleday_autoset varchar(20),
	bill_cycle_day_id varchar(32),
	communication_profile_id varchar(50),
	created_by_id varchar(32),
	created_on varchar(50),
	credit_balance DECIMAL(22,9),
	crm_account_id varchar(100),
	currency_id varchar(32),
	csr_name varchar(50),
	id varchar(32) primary key distkey,
	industry_segment varchar(20),
	invoice_delivery_prefs_email boolean,
	invoice_delivery_prefs_print boolean,
	invoice_template_id varchar(32),
	last_invoice_date varchar(50),
	key_metrics_id varchar(32),
	customer_name varchar(255),
	notes varchar(500),
	parent_id varchar(50),
	gateway_id varchar(32),
	payment_term_id varchar(32),
	po_number varchar(100),
	sales_rep_name varchar(50),
	status varchar(20),
	taxexempt_certificate_id varchar(32),
	taxexempt_certificate_type varchar(32),
	taxexempt_description varchar(500),
	taxExempt_effective_date varchar(50),
	taxExempt_expiration_date  varchar(50),
	taxExempt_issuing_jurisdiction varchar(32),
	taxexempt_status varchar(32),
	field_decimal_1 DECIMAL(22,9),
	updated_by_id varchar(32),
	updated_on varchar(50)
);



CREATE TABLE subscription 
(
  autoRenew                          BOOLEAN,
  cancelledDate                      datetime,
  acceptancedatetime                 date,
  contractdatetime                   date,
  createdById                        VARCHAR(32),
  createdDate                        DATE,
  creatorAccountId                   VARCHAR(32),
  creator_invoice_owner_account_id   VARCHAR(32),
  id                                 VARCHAR(32) PRIMARY KEY distkey,
  initial_term                       INTEGER,
  invoice_owner_id                   VARCHAR(32),
  invoice_separate                   BOOLEAN,
  subscription_name                  VARCHAR(100),
  notes                              VARCHAR(500),
  subscriptionCreatedTime            date,
  original_id                        VARCHAR(32),
  previous_subscription_id           VARCHAR(32),
  renewal_setting                    VARCHAR(50),
  reneval_term                       INTEGER,
  service_activation_date            date,
  status                             VARCHAR(32),
  subscription_end_date              DATE,
  subscription_start_date            DATE,
  term_end_date                      DATE,
  term_start_date                    DATE,
  term_type                          VARCHAR(32),
  updated_by_id                      VARCHAR(32),
  updated_on                         date,
  VERSION                            INTEGER
)
sortkey (version,status);
